### ISSUE TITLE
Split UI and Payment Backend from core cart

### ISSUE THREAD

**Issue by jimmiebtlr** [nate-strauser/meteor-cart#4]
Would you be interested in splitting the UI and Payment backend from the core functionality of the cart?  If so I would be interested in helping out.

**Comment by nate-strauser** [comment]
can you expand on what you are thinking here?  i suppose a pattern like what the useraccounts package does could be nice.  eg cart-core, cart-stripe, cart-balanced, etc

is that what you had in mind?

**Comment by jimmiebtlr** [comment]
That is what I had in mind.

**Comment by nate-strauser** [comment]
ok - i'm game for this - shouldn't be too hard actually - just need to pull
out the 'pay' button behavior and have that be a separate package

**Comment by nate-strauser** [comment]
i'll split the package into 2 parts soon - how do you want to help out after that?  want to add another payments backend?  balanced would be a good choice, i really only went with stripe b/c they provide the credit card form which i didn't want to manually build - could use something like http://jessepollak.github.io/card/

**Comment by jimmiebtlr** [comment]
I was thinking balanced.  Card looks great.  It may also be good to separate out the UI, to more easily allow other styling frameworks.

**Comment by nate-strauser** [comment]
i think this sounds good and will get to it soon - been wrapped up with
some other things lately

**Comment by NetOpWibby** [comment]
@jimmiebtlr Do you have a PR, or a custom implementation for this? I'm interested in doing something similar for my shop.

**Comment by jimmiebtlr** [comment]
Not currently

**Comment by jimmiebtlr** [comment]
I've created a cart only package (no ui or payment) at https://github.com/ElevateDev/meteor-cart.
