### ISSUE TITLE
Is there a way to put Stripe keys somewhere?

### ISSUE THREAD

**Issue by NetOpWibby** [nate-strauser/meteor-cart#5]
I would prefer not to use the extra parameter to make this work.

Thanks for creating this btw, I'm trying to get my shop launched on April 3rd and this is the last part.

**Comment by nate-strauser** [comment]
stripe keys need to be in settings for stripe to initialize automatically

## 

you could alter the package and set key here on the client
https://github.com/nate-strauser/meteor-cart/blob/d0a181394f07c08518381794b5c1c7b20bbf2b9e/lib/client/cart.js#L103

and call init stripe with this call on the server
https://github.com/nate-strauser/meteor-cart/blob/master/lib/both/environment.js#L20

## 

you'll get an error in the console, but if you manually init stripe it will still work

---

closing this as i see no real problem with forcing the use of meteor.settings - it is much more user friendly and suitable for a production environment
