### ISSUE TITLE
How do I style /cart?

### ISSUE THREAD

**Issue by NetOpWibby** [nate-strauser/meteor-cart#6]
Like the title says. I've included this in my project, but I don't know where to go from here. I'm going to keep searching though.

**Comment by NetOpWibby** [comment]
I see the HTML is being written in the compiled source of this plugin. I just copied the entire script into my `client` folder and removed this plugin. Not the ideal way to go about things, but it works.

**Comment by adrianricardo** [comment]
I'd also like to know the right way to do this

**Comment by adrianricardo** [comment]
perhaps this? https://github.com/aldeed/meteor-template-extension
