### ISSUE TITLE
Cart-userOrders

### ISSUE THREAD

**Issue by chiester** [nate-strauser/meteor-cart#7]
Was cart-userOrders never implemented?

**Comment by nate-strauser** [comment]
not sure exactly what you mean...

there is the publication of that name https://github.com/nate-strauser/meteor-cart/blob/master/lib/server/publications.js#L1

is that what you were looking for?

**Comment by chiester** [comment]
Sorry, I should have added more detail. I see the publication, but I don't see a subscription or any queries or use of this collection in the example.

**Comment by nate-strauser** [comment]
see here - https://github.com/nate-strauser/meteor-cart/blob/master/lib/client/cart.js#L2

basically the 2 pub/sub channels (user based and device based) make sure all the orders are sent down to the client

the example app doesn't use these directly but the package client side code does

i believe this issue should be closed now as i don't think there is a problem with the package - feel free to ask other questions or make another issue if you find a problem
